
CC=/usr/bin/c99

CFLAGS= -I$(IDIR) -Xc -g -errfmt=error -erroff=%none \
	-xmemalign=8s -errshort=full -xstrconst -xildoff -m64 -xnolibmil \
	-xcode=pic32 -xregs=no%appl -xlibmieee -ftrap=%none -xarch=sparc -mc \
	-xs -xbuiltin=%none -xdebugformat=dwarf -xunroll=1

CPPFLAGS=-D_TS_ERRNO -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

LIBS = -lm -lrt
LDIR=/opt/bw/lib
IDIR=/opt/bw/include
RPATH=/opt/bw/lib

SRCS = ./cube_roots.c \
	../sysinfo/sysinfo.c


OBJS = ./cube_roots.o \
	../sysinfo/sysinfo.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS) -I. -I$(IDIR)

cube_roots: cube_roots.o $(OBJS)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) -L$(LDIR) -R$(RPATH) $(LIBS)

clean:
	rm -f $(OBJS) cube_roots cube_roots.o
