
CC=/usr/bin/cc

CFLAGS= -std=iso9899:2011 -pedantic -pedantic-errors -Weverything \
	-Wno-reserved-id-macro -Wno-missing-prototypes -m64 -g -O0 \
	-fno-fast-math -fno-builtin

CPPFLAGS=-D_TS_ERRNO -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE

SRCS = fg.c ../sysinfo/sysinfo.c
OBJS = fg.o ../sysinfo/sysinfo.o

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

fg: $(OBJS)
	$(CC) -o $@ $(OBJS) $(CFLAGS) $(CPPFLAGS)

clean:
	rm -f $(OBJS) fg
