
CC=/usr/bin/cc

CFLAGS= -std=iso9899:1999 -pedantic -pedantic-errors -Weverything \
	-Wno-reserved-id-macro -Wno-missing-prototypes -m64 -g -O0 \
	-fno-fast-math -fno-builtin -Wno-unsafe-buffer-usage

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 \
	-D_XOPEN_SOURCE=600

LIBS=	-lm

SRCS = filetimes.c ../../stat_test/file_stat_err.c \
	../../sysinfo/sysinfo.c ../../sysinfo/endian.c

OBJS = filetimes.o ../../stat_test/file_stat_err.o \
	../../sysinfo/sysinfo.o ../../sysinfo/endian.o

.PHONY: all
all: filetimes

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

filetimes: $(OBJS)
	$(CC) -o $@ ${OBJS} $(CFLAGS) $(CPPFLAGS) $(LIBS)

clean:
	rm -f $(OBJS) filetimes

