
CC=/usr/bin/c99

CFLAGS= -I$(IDIR) -Xc -g -errfmt=error -erroff=%none \
	-xmemalign=8s -errshort=full -xstrconst -xildoff -m64 -xnolibmil \
	-xcode=pic32 -xregs=no%appl -xlibmieee -ftrap=%none -xarch=sparc -mc \
	-xs -xbuiltin=%none -xdebugformat=dwarf -xunroll=1

CPPFLAGS= -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_FILE_OFFSET_BITS=64 -D_XOPEN_SOURCE=600

OBJ = ../../sysinfo/sysinfo.o bmp_header.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

bmp_header: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) -lm

clean:
	rm -f bmp_header ../../sysinfo/sysinfo.o
