
CC=/usr/bin/c99

CFLAGS= -I$(IDIR) -Xc -g -errfmt=error -erroff=%none \
	-xmemalign=8s -errshort=full -xstrconst -xildoff -m64 -xnolibmil \
	-xcode=pic32 -xregs=no%appl -xlibmieee -ftrap=%none -xarch=sparc -mc \
	-xs -xbuiltin=%none -xdebugformat=dwarf -xunroll=1

CPPFLAGS=-D_TS_ERRNO -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

LIBS = -lm -lgmp -lmpfr
LDIR = /opt/bw/lib
IDIR = /opt/bw/include

SRCS = ./mpfr_set_str.c

OBJS = ./mpfr_set_str.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS) -I$(IDIR)

mpfr_set_str: $(OBJS)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) -L$(LDIR) -R$(LDIR) $(LIBS)

clean:
	rm -f $(OBJS) mpfr_set_str
