
CC=/usr/bin/c99

CFLAGS= -Xc -g -errfmt=error -erroff=%none \
	-xmemalign=8s -errshort=full -xstrconst -xildoff -m64 -xnolibmil \
	-xcode=pic32 -xregs=no%appl -xlibmieee -ftrap=%none -xarch=sparc -mc \
	-xs -xbuiltin=%none -xdebugformat=dwarf -xunroll=1

CPPFLAGS=-D_TS_ERRNO -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE -D_X_OPEN_SOURCE=600

IDIR=/opt/bw/include
LDIR=/opt/bw/lib

LDFLAGS = -L/opt/bw/lib
LD_OPTIONS = -R/opt/bw/lib -L/opt/bw/lib
LD_RUN_PATH = /opt/bw/lib

LIBS = -lm -lrt

SRC = schadenfreude.c tt800.c ../time_and_date/timediff.c ../sysinfo/sysinfo.c
OBJ = schadenfreude.o tt800.o ../time_and_date/timediff.o ../sysinfo/sysinfo.o

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) -I$(IDIR) $(CPPFLAGS)

schadenfreude: $(OBJ)
	$(CC) -o $@ $(OBJ) $(CFLAGS) $(LD_OPTIONS) $(CPPFLAGS) -L$(LDIR) $(LIBS)

clean:
	rm -f $(OBJ) schadenfreude
