#!/bin/ksh
/usr/xpg4/bin/date -u > ./roul_log.$$
/bin/printf "\ntrial 1"
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$

/bin/printf " 2"
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$

/bin/printf " 3"
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$

/bin/printf " 4"
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$

/bin/printf " 5"
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$

/bin/printf " 6"
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$

/bin/printf " 7"
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$

/bin/printf " 8"
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$

/bin/printf " 9"
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$

/bin/printf " 10"
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$
./roul 6550 25 PROFIT 50 >> ./roul_log.$$

/bin/printf " done\n"

/usr/xpg4/bin/ls -lapb ./roul_log.$$

/usr/xpg4/bin/grep -v "GMT" ./roul_log.29635 | \
/usr/xpg4/bin/grep "^FINAL" | \
/usr/xpg4/bin/grep -v "FINAL\ \:\ \ \ 2" | \
/usr/xpg4/bin/awk 'BEGIN{ FS=":" }{ print $2 ":" $3 }' | \
/usr/xpg4/bin/sort -n | /usr/bin/cat -n - | \
/usr/xpg4/bin/tail -1 | /usr/xpg4/bin/awk '{ print $1 "% fail" }'

