
CC=/usr/bin/gcc

CFLAGS= -std=iso9899:1999 -g -O0 -m64 -fno-builtin -mcpu=970 \
	-mpowerpc64 -mno-altivec -msecure-plt -mno-vsx \
	-mno-quad-memory -mno-float128 -mhard-float \
	-mno-float128-hardware -mno-avoid-indexed-addresses \
	-mno-isel -mno-crypto -mno-htm -mno-quad-memory-atomic \
	-mno-multiple -mupdate -mno-avoid-indexed-addresses \
	-mregnames -mno-recip -fno-unsafe-math-optimizations \
	-fno-fast-math -mfull-toc -mno-fp-in-toc -mno-sum-in-toc \
	-ffp-contract=off -Wl,-rpath=/opt/bw/lib,--enable-new-dtags

CPPFLAGS= -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

LIBS = -lm

SRCS = report.c sysinfo.c endian.c

OBJS = report.o sysinfo.o endian.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

report: report.o $(OBJS)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) $(LIBS)

clean:
	rm -f $(OBJS) report.o sysinfo.o report
