CC=/usr/bin/cc

CFLAGS= -std=iso9899:1999 -m64 -g -O0 -pedantic -pedantic-errors \
	-fno-fast-math -fno-builtin

CPPFLAGS= -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

LIBS = -lm

SRCS = report.c sysinfo.c

OBJS = report.o sysinfo.o

.PHONY: all
all: report

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

report: $(OBJS)
	$(CC) -o $@ ${OBJS} $(CFLAGS) $(CPPFLAGS) $(LIBS)

clean:
	rm -f $(OBJS) report
