
# CC=/opt/bw/gcc9/bin/x86_64-redhat-linux-gcc-9.2.0 
CC=/usr/bin/cc

CFLAGS= -std=iso9899:1999 -m64 -O0 -g -fno-builtin \
	-pedantic -pedantic-errors \
	-march=k8 -mtune=k8 -mieee-fp -mhard-float -mpc80 \
	-fno-fast-math -malign-double -mno-mmx \
	-m128bit-long-double -mlong-double-80 \
	-mstackrealign -mpreferred-stack-boundary=4

CPPFLAGS=-D_TS_ERRNO -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

LIBS = -lm

SRCS = report.c sysmem.c sysinfo.c

OBJS = report.o sysmem.o sysinfo.o

.PHONY: all
all: report

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

report: $(OBJS)
	$(CC) -o $@ ${OBJS} $(CFLAGS) $(CPPFLAGS) $(LIBS)

clean:
	rm -f $(OBJS) report.o sysmem.o sysinfo.o report
