
CC=/usr/bin/cc

CFLAGS= -std=iso9899:1999 -pedantic -pedantic-errors -Weverything \
	-march=rv64imafdc -mabi=lp64d \
	-fno-fast-math -fno-builtin \
	-fno-color-diagnostics \
	-Wno-reserved-id-macro -Wno-missing-prototypes -m64 -g -O0 \
	-Wno-reserved-identifier -Wno-unsafe-buffer-usage

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 \
	-D_XOPEN_SOURCE=600

LIBS = -lm

SRCS = report.c sysinfo.c endian.c

OBJS = report.o sysinfo.o endian.o

.PHONY: all
all: report

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

report: $(OBJS)
	$(CC) -o $@ ${OBJS} $(CFLAGS) $(CPPFLAGS) $(LIBS)

clean:
	rm -f $(OBJS) report

