CC=/usr/bin/cc

CFLAGS= -I$(IDIR) -std=iso9899:1999 -fno-builtin -g -march=armv7-a \
	-mtune=cortex-a17 -mfpu=vfpv4-d16 \
	-marm -mtls-dialect=gnu2 -pedantic -pedantic-errors \
   	-Wl,-rpath=/opt/bw/lib,--enable-new-dtags \
	-mno-sched-prolog -mlittle-endian

CPPFLAGS= -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

LIBS = -lm

SRCS = report.c sysinfo.c

OBJS = report.o sysinfo.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

report: report.o $(OBJS)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) $(LIBS)

clean:
	rm -f $(OBJS) report
