
CC=/opt/developerstudio12.6/bin/c99

CFLAGS= -Xc -g -errfmt=error -erroff=%none -xmemalign=8s -errshort=full \
	-xstrconst -xildoff -m64 -xnolibmil -xcode=pic32 -xregs=no%appl \
	-xlibmieee -ftrap=%none -xarch=sparc -mc -xs -xbuiltin=%none \
	-xdebugformat=dwarf -xunroll=1

CPPFLAGS= -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

LIBS = -lm -lrt

SRCS = report.c sysinfo.c

OBJS = report.o sysinfo.o

.PHONY: all
all: report

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

report: $(OBJS)
	$(CC) -o $@ ${OBJS} $(CFLAGS) $(CPPFLAGS) $(LIBS)

clean:
	rm -f $(OBJS) report
