
CC= /usr/bin/gcc

CFLAGS= -std=iso9899:1999 -g -O0 -mcpu=21164 -mgas \
	-mexplicit-relocs -fno-fast-math -fno-builtin \
	-fno-unsafe-math-optimizations \
	-mno-soft-float -mfp-trap-mode=sui \
	-mfp-rounding-mode=n -mtrap-precision=i \
	-mieee-with-inexact -mieee-conformant

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64

LIBS = -lm

SRCS = report.c sysinfo.c endian.c

OBJS = report.o sysinfo.o endian.o

.PHONY: all
all: report

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

report: $(OBJS)
	$(CC) -o $@ ${OBJS} $(CFLAGS) $(CPPFLAGS) $(LIBS)

clean:
	rm -f $(OBJS) report
