
IDIR = .

CC=/usr/bin/gcc

CFLAGS= -I$(IDIR) -std=iso9899:1999 -pedantic -fno-builtin -g -m64 \
	-mcpu=970 -mno-altivec -mno-isel -mno-vsx \
	-mno-crypto -mno-htm -mno-quad-memory-atomic -mfull-toc \
	-mno-multiple -mupdate -mno-avoid-indexed-addresses \
	-ffp-contract=off -mno-mulhw \
	-mno-dlmzb -mno-bit-align -mno-strict-align -mbig -mregnames \
	-mno-recip -fno-unsafe-math-optimizations

CPPFLAGS= -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

LDIR=/opt/bw/lib
IDIR=/opt/bw/include
LIBS=-lm

SRCS = schmuck.c tt800.c ../sysinfo/sysinfo.c \
		../time_and_date/timediff.c

OBJS = schmuck.o tt800.o ../sysinfo/sysinfo.o \
   		../time_and_date/timediff.o

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) -I$(IDIR) $(CPPFLAGS)

schmuck: $(OBJS)
	$(CC) -o $@ $(OBJS) $(CFLAGS) $(CPPFLAGS) -L$(LDIR) $(LIBS)

clean:
	rm -f $(OBJS) schmuck
