
# CC=/opt/bw/gcc9/bin/x86_64-redhat-linux-gcc-9.2.0 
CC=/usr/bin/cc

CFLAGS= -std=iso9899:1999 -m64 -O0 -g -fno-builtin \
	-pedantic -pedantic-errors \
	-march=k8 -mtune=k8 -mieee-fp -mhard-float -mpc80 \
	-fno-fast-math -malign-double -mno-mmx \
	-m128bit-long-double -mlong-double-80 \
	-mstackrealign -mpreferred-stack-boundary=4

CPPFLAGS= -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

LDIR=/usr/local/lib
IDIR=/usr/local/include

SRCS = bsort.c
OBJS = bsort.o

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) -I$(IDIR) $(CPPFLAGS)

bsort: $(OBJS)
	$(CC) -o $@ $(OBJS) $(CFLAGS) $(CPPFLAGS) -L$(LDIR)

clean:
	rm -f $(OBJS) bsort
