
CC=/usr/bin/gcc

CFLAGS= -I$(IDIR) -std=iso9899:1999 -m64 -g -O0 -pedantic \
	-pedantic-errors -fno-builtin -fno-fast-math -mhard-float \
	-mno-app-regs -mflat -mhard-quad-float \
	-mno-unaligned-doubles -mno-faster-structs \
	-mcpu=ultrasparc -mtune=ultrasparc -mno-vis -mno-cbcond \
	-mno-fmaf -mno-fsmuld -mno-popc -mno-subxc -mcmodel=medany \
	-mmemory-model=tso

CPPFLAGS=-D_TS_ERRNO -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

LDIR=/usr/local/lib
IDIR=/usr/local/include

SRCS = bsort.c
OBJS = bsort.o

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) -I$(IDIR) $(CPPFLAGS)

bsort: $(OBJS)
	$(CC) -o $@ $(OBJS) $(CFLAGS) $(CPPFLAGS) -L$(LDIR) $(LIBS)

clean:
	rm -f $(OBJS) bsort
