
CC=/usr/bin/c99

CFLAGS= -Xc -g -errfmt=error -erroff=%none \
	-xmemalign=8s -errshort=full -xstrconst -xildoff -m64 -xnolibmil \
	-xcode=pic32 -xregs=no%appl -xlibmieee -ftrap=%none -xarch=sparc -mc \
	-xs -xbuiltin=%none -xdebugformat=dwarf -xunroll=1

CPPFLAGS= -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

LIBS = -lpthread -lrt -lm

SRCS = main.c fib_sleep.c dispatch.c \
	../sysinfo/sysinfo.c \
	../time_and_date/timediff.c \
	../pthread/fib.c

OBJS = main.o fib_sleep.o dispatch.o \
	../sysinfo/sysinfo.o \
	../time_and_date/timediff.o \
	../pthread/fib.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

main: main.o $(OBJS)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) $(LIBS)

clean:
	rm -f $(OBJS) main
