
CC=/usr/bin/cc

CFLAGS= -std=iso9899:1999 -pedantic -g -O0 -fno-builtin \
	-m64 -mcpu=970 -mno-altivec -mno-isel -mno-vsx -mno-crypto \
	-mno-htm -mno-quad-memory-atomic -mfull-toc -mno-multiple \
	-mupdate -mno-avoid-indexed-addresses -mno-dlmzb \
	-mno-bit-align -mno-strict-align -mbig -mregnames \
	-mno-recip -fno-unsafe-math-optimizations -pedantic-errors \
	-Wall

CPPFLAGS= -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

LIBS = -lpthread -lrt -lm

SRCS = main.c fib_sleep.c dispatch.c \
	   ../sysinfo/sysinfo.c \
	   ../time_and_date/timediff.c \
	   ../pthread/fib.c

OBJS = main.o fib_sleep.o dispatch.o \
	   ../sysinfo/sysinfo.o \
	   ../time_and_date/timediff.o \
	   ../pthread/fib.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

main: main.o $(OBJS)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) $(LIBS)

clean:
	rm -f $(OBJS) main
