
CC=/usr/bin/cc

CFLAGS= -std=iso9899:1999 -m64 -O0 -g -fno-builtin \
	-Wl,-rpath=/opt/bw/lib,--enable-new-dtags \
	-pedantic -pedantic-errors \
	-march=k8 -mtune=k8 -mieee-fp -mhard-float -mpc80 \
	-fno-fast-math -malign-double \
	-m128bit-long-double -mlong-double-80 \
	-mstackrealign -mpreferred-stack-boundary=4 -mno-mmx \

CPPFLAGS= -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

LIBS = -lpthread -lrt -lm

SRCS = main.c fib_sleep.c dispatch.c \
	   ../sysinfo/sysinfo.c \
	   ../time_and_date/timediff.c \
	   ../pthread/fib.c

OBJS = main.o fib_sleep.o dispatch.o \
	   ../sysinfo/sysinfo.o \
	   ../time_and_date/timediff.o \
	   ../pthread/fib.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

main: main.o $(OBJS)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) $(LIBS)

clean:
	rm -f $(OBJS) main
