
CC=/usr/bin/gcc

CFLAGS= -std=iso9899:1999 -m64 -g -O0 -pedantic -pedantic-errors \
	-fno-builtin -fno-fast-math -mhard-float -mno-app-regs -mflat \
	-msoft-quad-float -mno-unaligned-doubles -mno-faster-structs \
	-mcpu=niagara7 -mtune=niagara7 -mno-vis -mno-cbcond \
	-mno-fmaf -mno-fsmuld -mno-popc -mno-subxc

CPPFLAGS= -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600 -D_REENTRANT \
	-D_FILE_OFFSET_BITS=64

LIBS=	-lpthread -lrt -lm
IDIR=	/usr/include

include common.mk

