
CC=/usr/bin/cc

CFLAGS= -I$(IDIR) -std=iso9899:1999 -pedantic -pedantic-errors -m64 -g \
	-O0 -march=k8 -mtune=k8 -Wl,-rpath=/opt/bw/lib,--enable-new-dtags \
   	-fno-builtin -malign-double -mpc80

CPPFLAGS=-D_TS_ERRNO -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
		-D_XOPEN_SOURCE=600 -D_REENTRANT

LIBS = -lpthread -lrt -lm

OBJQ = ../sysinfo/sysinfo.o \
	q_work.o enqueue.o dequeue.o q_create.o \
	q_destroy.o do_work.o fib.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

q_work: $(OBJQ)
	$(CC) -o $@ $^ -L$(LDIR) $(CFLAGS) $(CPPFLAGS) -D_REENTRANT $(LIBS)

clean:
	rm -f *.o p0 q_work
