
CC=/usr/bin/cc

CFLAGS= -std=iso9899:1999 -pedantic -pedantic-errors \
	-fno-builtin -g -march=armv7-a \
	-mtune=cortex-a17 -mfpu=vfpv4-d16 \
	-marm -mtls-dialect=gnu2 -pedantic \
	-mno-sched-prolog -mlittle-endian

include common.mk
