
CC=/opt/developerstudio12.6/bin/c99

CFLAGS= -I$(IDIR) -Xc -g -errfmt=error -erroff=%none \
	-xmemalign=8s -errshort=full -xstrconst -xildoff -m64 -xnolibmil \
	-xcode=pic32 -xregs=no%appl -xlibmieee -ftrap=%none -xarch=sparc -mc \
	-xs -xbuiltin=%none -xdebugformat=dwarf -xunroll=1

CPPFLAGS=-D_TS_ERRNO -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600 -D_REENTRANT

LIBS = -lpthread -lrt -lm

OBJQ =	../sysinfo/sysinfo.o \
	q_work.o enqueue.o dequeue.o q_create.o \
	q_destroy.o do_work.o fib.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS) -D_REENTRANT

q_work: $(OBJQ)
	$(CC) -o $@ $^ -L$(LDIR) $(CFLAGS) $(CPPFLAGS) -D_REENTRANT $(LIBS)

clean:
	rm -f *.o q_work ../sysinfo/sysinfo.o
