
CC=/usr/bin/cc

CFLAGS= -I$(IDIR) -std=iso9899:1999 -m32 -g -O0 -fno-builtin \
	-march=i586 -mtune=i586 -mieee-fp -mhard-float -mpc80 \
	-fno-fast-math -mno-fancy-math-387 -malign-double \
	-m128bit-long-double -mlong-double-80 -mregparm=0 \
	-mstackrealign -mpreferred-stack-boundary=4 -mno-mmx \
	-mno-sse

CPPFLAGS= -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600 -D_REENTRANT

LIBS = -lpthread -lrt -lm

OBJQ = ../sysinfo/sysinfo.o \
	q_work.o enqueue.o dequeue.o q_create.o \
	q_destroy.o do_work.o fib.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS) -D_REENTRANT

q_work: $(OBJQ)
	$(CC) -o $@ $^ -L$(LDIR) $(CFLAGS) $(CPPFLAGS) -D_REENTRANT $(LIBS)

clean:
	rm -f *.o q_work ../sysinfo/sysmem.o ../sysinfo/sysinfo.o ../sysinfo/ru.o
