
CC=/usr/bin/cc

CFLAGS= -std=iso9899:1999 -m64 -g -O0 -pedantic -pedantic-errors \
	-march=rv64imafdc -mabi=lp64d \
	-Weverything -Wno-reserved-id-macro -Wno-unused-macros \
	-Wno-missing-prototypes -Wno-padded -fno-fast-math -fno-builtin

CPPFLAGS?= -D_LARGEFILE64_SOURCE \
		-D_XOPEN_SOURCE=600 -D_REENTRANT \
		-D_FILE_OFFSET_BITS=64

include common.mk
