
CC=/usr/bin/cc

CFLAGS= -I$(IDIR) -std=iso9899:1999 -pedantic -pedantic-errors \
   	-fno-builtin -g -march=armv7-a \
	-mtune=cortex-a17 -mfpu=vfpv4-d16 -mstructure-size-boundary=32 \
	-marm -mtls-dialect=gnu2 -pedantic -mno-sched-prolog -mlittle-endian

CPPFLAGS=-D_TS_ERRNO -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
		-D_XOPEN_SOURCE=600 -D_REENTRANT

LIBS = -lpthread -lrt -lm

OBJ = p0.o ru.o sysinfo.o sysmem.o

OBJQ = sysmem.o sysinfo.o q_work.o enqueue.o dequeue.o q_create.o \
	q_destroy.o do_work.o fibber.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

q_work: $(OBJQ)
	$(CC) -o $@ $^ -L$(LDIR) $(CFLAGS) $(CPPFLAGS) -D_REENTRANT $(LIBS)

p0: $(OBJ)
	$(CC) -o $@ $^ -L$(LDIR) $(CFLAGS) $(CPPFLAGS) $(LIBS)

clean:
	rm -f *.o p0 q_work
