
CC?=/usr/bin/gcc

CFLAGS= -std=iso9899:1999 -pedantic -pedantic-errors -m64 -g \
	-O0 -fno-builtin -march=k8 -mtune=k8 -mieee-fp -mhard-float \
	-fno-fast-math -mno-fancy-math-387 -m128bit-long-double -mstackrealign \
	-mpreferred-stack-boundary=8

LIBS=	-lpthread -lrt -lm

include fbsd_common.mk
