
CC=/usr/bin/cc

CFLAGS= -I$(IDIR) -std=iso9899:1999 -m64 -g -O0 -fno-builtin -march=k8 \
	-mtune=k8 -mieee-fp -mhard-float -mpc80 -fno-fast-math \
	-mno-fancy-math-387 -malign-double -m128bit-long-double \
	-mlong-double-80 -mstackrealign -mpreferred-stack-boundary=8 -mno-mmx

CPPFLAGS=-D_TS_ERRNO -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

OBJ = ../sysinfo/sysinfo.o ../sysinfo/sysmem.o endian.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

endian: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) -lm

clean:
	rm -f *.o endian ../sysinfo/sysinfo.o ../sysinfo/sysmem.o
