
CC=/usr/bin/cc

CFLAGS=-std=iso9899:1999 -pedantic -pedantic-errors -Weverything \
	-Wno-reserved-id-macro -Wno-unused-macros -m64 -g -O0 -fno-fast-math -fno-builtin

CPPFLAGS=-D_TS_ERRNO -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

OBJ = ../pthread/sysinfo.o ../pthread/sysmem.o endian.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

endian: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS)

clean:
	rm -f *.o endian ../pthread/sysinfo.o ../pthread/sysmem.o
