
CC=/usr/bin/gcc

CFLAGS= -std=iso9899:1999 -pedantic -pedantic-errors \
   	-g -O0 -m64 -fno-builtin -fno-fast-math \
	-ffp-contract=off -fno-unsafe-math-optimizations -malign-double \
	-march=k8 -mtune=k8 -mieee-fp -mhard-float -mpc80 \
	-m128bit-long-double -mlong-double-80 -mstackrealign \
	-mpreferred-stack-boundary=8

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=600

LDIR=/usr/local/lib
IDIR=/usr/local/include
LIBS= -lm

SRCS = pmt.c
OBJS = pmt.o

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) -I$(IDIR) $(CPPFLAGS)

pmt: $(OBJS)
	$(CC) -o $@ $(OBJS) $(CFLAGS) $(CPPFLAGS) -L$(LDIR) $(LIBS)

clean:
	rm -f $(OBJS) pmt

