
CC=/opt/developerstudio12.6/bin/c99

CFLAGS= -m64 -xarch=sparc -Xc -g -mc -xs -errfmt=error \
	-erroff=%none -errshort=full -errtags=yes -errwarn=%none \
	-ftrap=%none -xbuiltin=%none -xildoff -xlibmieee -xstrconst \
	-xcode=pic32 -xmemalign=8s -xnolibmil -xunroll=1 -xregs=no%appl \
	-xdebugformat=dwarf

IDIR = /opt/bw/include
LDIR = /opt/bw/lib

include common.mk
