
CC=/usr/bin/cc

CFLAGS= -I$(IDIR) -std=iso9899:1999 -m64 -O0 -g -fno-builtin \
	-pedantic -pedantic-errors \
	-march=k8 -mtune=k8 -mieee-fp -mhard-float -mpc80 \
	-fno-fast-math -malign-double \
	-m128bit-long-double -mlong-double-80 \
	-mstackrealign -mpreferred-stack-boundary=4 -mno-mmx \

CPPFLAGS=-D_TS_ERRNO -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

LIBS = -lpng
LDIR = /opt/bw/lib
IDIR = /opt/bw/include
LDFLAGS = -L/opt/bw/lib
LD_OPTIONS = -64 -R/opt/bw/lib -L/opt/bw/lib
LD_RUN_PATH = /opt/bw/lib

SRC = png_convert_to_8bit.c
OBJ = png_convert_to_8bit.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS) -I$(IDIR)

png_convert_to_8bit: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) -Wl,-rpath=$(LDIR) -L$(LDIR) $(LIBS)

clean:
	rm -f $(OBJ) png_convert_to_8bit
