
CC=/usr/bin/gcc

CFLAGS = -std=iso9899:1999 -pedantic -pedantic-errors \
	-g -O0 -fno-builtin -m64 -fno-unsafe-math-optimizations

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=600

LIBS = -lX11 -lrt -lm

include common.mk
