
CC=/usr/bin/cc

CFLAGS= -I$(IDIR) -std=iso9899:1999 -m64 -O0 -g -fno-builtin \
	-Wl,-rpath=/opt/bw/lib,--enable-new-dtags \
	-pedantic -pedantic-errors \
	-march=k8 -mtune=k8 -mieee-fp -mhard-float \
	-fno-fast-math -malign-double \
	-m128bit-long-double \
	-mstackrealign -mpreferred-stack-boundary=8 -mno-mmx \

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=600

include common.mk
