
CC=/usr/bin/gcc

CFLAGS = -std=iso9899:1999 -pedantic -pedantic-errors \
	-g -O0 -fno-builtin -fno-unsafe-math-optimizations \
	-march=rv64imafdc -mabi=lp64d

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=600

LIBS = -lX11 -lrt -lm

include common.mk
