
CC=/usr/bin/cc

CFLAGS= -std=iso9899:1999 -m64 -g -O0 -pedantic -pedantic-errors \
	-Weverything -Wno-reserved-id-macro -Wno-unused-macros \
	-Wno-missing-prototypes -Wno-padded -fno-fast-math -fno-builtin \
	-Wno-disabled-macro-expansion -Wl,-rpath=/opt/bw/lib,-enable-new-dtags

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=600

LDIR=/opt/bw/lib
IDIR=/opt/bw/include
LIBS= -lcurl

SRCS = dlist_curl.c ../sysinfo/sysinfo.c
OBJS = dlist_curl.o ../sysinfo/sysinfo.o

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) -I$(IDIR) $(CPPFLAGS)

dlist_curl: $(OBJS)
	$(CC) -o $@ $(OBJS) $(CFLAGS) $(CPPFLAGS) -L$(LDIR) $(LIBS)

clean:
	rm -f $(OBJS) dlist_curl
