
CC=/usr/bin/gcc

CFLAGS= -std=iso9899:1999 -m32 -g -O0 -pedantic -pedantic-errors \
		-fno-fast-math -fno-builtin

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=600

LDIR=/opt/bw/lib
IDIR=/opt/bw/include
LIBS= -lcurl -lm

SRCS = dlist_curl.c ../sysinfo/sysinfo.c
OBJS = dlist_curl.o ../sysinfo/sysinfo.o

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) -I$(IDIR) $(CPPFLAGS)

dlist_curl: $(OBJS)
	$(CC) -o $@ $(OBJS) $(CFLAGS) $(CPPFLAGS) -L$(LDIR) $(LIBS)

clean:
	rm -f $(OBJS) dlist_curl
