
# CC=/opt/bw/gcc9/bin/x86_64-redhat-linux-gcc-9.2.0 
CC=/usr/bin/cc

CFLAGS= -std=iso9899:1999 -m64 -O0 -g -fno-builtin \
	-pedantic -pedantic-errors \
	-march=k8 -mtune=k8 -mieee-fp -mhard-float -mpc80 \
	-fno-fast-math -malign-double -mno-mmx \
	-m128bit-long-double -mlong-double-80 \
	-mstackrealign -mpreferred-stack-boundary=4

CPPFLAGS= -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

SRCS = collatz.c collatz_f.c

OBJS = collatz.o collatz_f.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

collatz: collatz.o $(OBJS)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS)

clean:
	rm -f $(OBJS) collatz
