
CC=/usr/bin/gcc

CFLAGS= -std=iso9899:1999 -pedantic -pedantic-errors \
	-g -O0 -m64 -fno-builtin -fno-fast-math \
	-ffp-contract=off -fno-unsafe-math-optimizations \
	-malign-double \
	-march=k8 -mtune=k8 -mieee-fp -mhard-float \
	-m128bit-long-double \
	-mpreferred-stack-boundary=8

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 \
		-D_XOPEN_SOURCE=600

SRCS = c_out.c c_do.c collatz.c
OBJS = c_out.o c_do.o collatz.o

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

collatz: $(OBJS)
	$(CC) -o $@ $(OBJS) $(CFLAGS) $(CPPFLAGS)

clean:
	rm -f $(OBJS) collatz

