
CC= /usr/bin/cc

CFLAGS= -m64 -O3

CPPFLAGS= -D_LARGEFILE64_SOURCE

LDIR= /usr/local/lib
IDIR= /usr/local/include

SRCS = c_out.c c_do.c collatz.c
OBJS = c_out.o c_do.o collatz.o

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) -I$(IDIR) $(CPPFLAGS)

collatz: $(OBJS)
	$(CC) -o $@ $(OBJS) $(CFLAGS) $(CPPFLAGS) -L$(LDIR) $(LIBS)

clean:
	rm -f $(OBJS) collatz

