
CC=/usr/bin/gcc

CFLAGS= -std=iso9899:1999 -pedantic -g -O0 -fno-builtin -m64 \
	-mcpu=970 -mno-altivec -mno-isel -mno-vsx \
	-mno-crypto -mno-htm -mno-quad-memory-atomic -mfull-toc \
	-mno-multiple -mupdate -mno-avoid-indexed-addresses \
	-mno-dlmzb -mno-bit-align -mno-strict-align -mbig -mregnames \
	-mno-recip -fno-unsafe-math-optimizations -pedantic-errors \
	-Wall

CPPFLAGS= -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

SRCS = collatz.c collatz_f.c c_out.c
OBJS = collatz.o collatz_f.o c_out.o

%.o: %.c
	$(CC) -I. -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

collatz: $(OBJS)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS)

clean:
	rm -f $(OBJS) collatz
