
CC= /usr/bin/cc

CFLAGS= -std=iso9899:1999 -pedantic -pedantic-errors \
	-m64 -g -O0 -fno-fast-math -fno-builtin \
	-fno-color-diagnostics \
	-Weverything -Wno-reserved-id-macro \
	-Wno-missing-prototypes -Wno-padded \
	-Wno-unsafe-buffer-usage

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 \
		-D_XOPEN_SOURCE=600

SRCS = c_out.c c_do.c collatz.c
OBJS = c_out.o c_do.o collatz.o

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

collatz: $(OBJS)
	$(CC) -o $@ $(OBJS) $(CFLAGS) $(CPPFLAGS)

clean:
	rm -f $(OBJS) collatz

