
CC=/usr/bin/gcc

CFLAGS= -std=iso9899:1999 -m64 -g -O0 -pedantic \
	-pedantic-errors -fno-builtin -fno-fast-math -mhard-float \
	-mno-app-regs -mflat -mhard-quad-float \
	-mno-unaligned-doubles -mno-faster-structs \
	-mcpu=ultrasparc -mtune=ultrasparc -mno-vis -mno-cbcond \
	-mno-fmaf -mno-fsmuld -mno-popc -mno-subxc -mcmodel=medany \
	-mmemory-model=tso

CPPFLAGS=-D_TS_ERRNO -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

LIBS = -lm -lgmp -lmpfr

IDIR=/opt/bw/include
LDIR=/opt/bw/lib

SRC = mpfr_ver.c ../time_and_date/timediff.c ../sysinfo/sysinfo.c
OBJ = mpfr_ver.o ../time_and_date/timediff.o ../sysinfo/sysinfo.o

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) -I$(IDIR) $(CPPFLAGS)

mpfr_ver: $(OBJ)
	$(CC) -o $@ $(OBJ) $(CFLAGS) -Wl,-rpath=$(LDIR),--enable-new-dtags $(CPPFLAGS) -L$(LDIR) $(LIBS)

clean:
	rm -f $(OBJ) mpfr_ver
