
CC=/usr/bin/cc

CFLAGS= -std=iso9899:1999 \
	-pedantic -pedantic-errors \
	-march=rv64imafdc -mabi=lp64d -m64 -g -O0 \
	-fno-builtin -fno-fast-math -ffp-contract=off \
	-fno-color-diagnostics \
	-Weverything -Wno-reserved-id-macro \
	-Wno-padded -Wno-disabled-macro-expansion \
	-Wno-sign-conversion -Wno-extra-semi-stmt \
	-Wno-reserved-identifier -Wno-unused-macros \
	-Wno-cast-function-type-strict \
	-Wno-strict-prototypes -Wno-unsafe-buffer-usage

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_XOPEN_SOURCE=600

LIBS=	-lgmp -lmpfr -lcrypto

include fg_common.mk

