CC=/usr/bin/cc

CFLAGS= -I$(IDIR) -std=iso9899:1999 -fno-builtin -g -march=armv7-a \
	-mtune=cortex-a17 -mfpu=vfpv4-d16 -mstructure-size-boundary=32 \
	-marm -mtls-dialect=gnu2 -pedantic -Wl,-rpath=/opt/bw/lib \
	-mno-sched-prolog -mlittle-endian

CPPFLAGS=-D_TS_ERRNO -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=600
LIBS = -lm -lgmp -lmpfr

IDIR=/opt/bw/include
LDIR=/opt/bw/lib

SRC = mpfr_ver.c \
	../time_and_date/timediff.c \
	../pthread/sysinfo.c \
   	../pthread/sysmem.c

OBJ = mpfr_ver.o \
	  ../time_and_date/timediff.o \
	  ../pthread/sysinfo.o \
	  ../pthread/sysmem.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS) -I$(IDIR)

mpfr_ver: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) -L$(LDIR) $(LIBS)

clean:
	rm -f $(OBJ) mpfr_ver.o mpfr_ver pi*
