
CC=/opt/developerstudio12.6/bin/cc

CFLAGS= -std=iso9899:1999 -m64 -xarch=sparc -g -xO0 -mc -xs \
	-errfmt=error -erroff=%none -errshort=full -errtags=yes \
	-errwarn=%none -ftrap=%none -xbuiltin=%none -xildoff \
	-xlibmieee -xstrconst -xcode=pic32 -xmemalign=8s \
	-xnolibmil -xunroll=1 -xdepend=no -xregs=no%appl \
	-xdebugformat=dwarf

CPPFLAGS= -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE -D_TS_ERRNO \
	-D_FILE_OFFSET_BITS=64 -D_XOPEN_SOURCE=600

IDIR=/opt/bw/include
LDIR=/opt/bw/lib
ITIME=	../time_and_date
ISYSINFO=	../sysinfo

LDFLAGS = -L/opt/bw/lib
LD_OPTIONS = -R/opt/bw/lib -L/opt/bw/lib
LD_RUN_PATH = /opt/bw/lib

LIBS = -lm -lgmp -lmpfr -lcrypto -lrt

SRC = ../sysinfo/sysinfo.c ../sysinfo/endian.c \
	../time_and_date/tdiff.c gmp_mpfr_ver.c fgruenberger.c

OBJ = ../sysinfo/sysinfo.o ../sysinfo/endian.o \
	../time_and_date/tdiff.o gmp_mpfr_ver.o fgruenberger.o

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) -I$(IDIR) -I$(ITIME) -I$(ISYSINFO) $(CPPFLAGS)

fgruenberger: $(OBJ)
	$(CC) -o $@ $(OBJ) $(CFLAGS) $(LD_OPTIONS) $(CPPFLAGS) -L$(LDIR) $(LIBS)

clean:
	rm -f $(OBJ) fgruenberger
