
CC?=/usr/bin/cc

IDIR=/opt/bw/include
LDIR=/opt/bw/lib
LIBS = -lm -lgmp -lmpfr

CFLAGS= -I$(IDIR) -std=iso9899:1999 -pedantic -pedantic-errors \
	-m64 -g -O0 -fno-builtin \
	-march=k8 -mtune=k8 -mieee-fp -mhard-float \
	-fno-fast-math -malign-double \
	-m128bit-long-double \
	-mstackrealign -mpreferred-stack-boundary=8 -mno-mmx \
	-Wl,-rpath=$(LDIR),--enable-new-dtags

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=600

include common.mk
