
CC?= /usr/bin/gcc

CFLAGS= -std=iso9899:1999 -pedantic -pedantic-errors \
	-m64 -g -O0 -fno-builtin \
	-march=k8 -mtune=k8 -mieee-fp -mhard-float \
	-fno-fast-math -malign-double \
	-m128bit-long-double \
	-mstackrealign -mpreferred-stack-boundary=8 -mno-mmx

LIBS=	-lgmp -lmpfr -lcrypto -lm

LDIR=  /usr/local/lib
IDIR=  /usr/local/include
LD_RUN_PATH= /usr/local/lib

include fg_common.mk

