
CC = /usr/bin/gcc

CFLAGS = -std=iso9899:1999 -g -O0 -fno-builtin -fno-fast-math \
	-mlittle-endian -mgnu-as -mgnu-ld -mregister-names \
	-mno-inline-int-divide -mno-inline-sqrt -ffp-contract=off \
	-mtune=itanium2 -mno-sched-br-data-spec \
	-mno-sched-ar-data-spec -mno-sched-control-spec \
	-msched-count-spec-in-critical-path \
	-Wl,-rpath=/opt/bw/lib,--enable-new-dtags

LIBS=	-lgmp -lmpfr -lcrypto -lm

include fg_common.mk

