
CC?= /usr/bin/gcc

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_XOPEN_SOURCE=600

CFLAGS= -std=iso9899:1999 -pedantic -pedantic-errors \
	-m64 -g -O0 -fno-builtin \
	-march=k8 -mtune=k8 -mieee-fp -mhard-float \
	-fno-fast-math -mno-fancy-math-387 -malign-double \
	-m128bit-long-double \
	-mstackrealign -mpreferred-stack-boundary=8 -mno-mmx

LIBS=	-lgmp -lm

include pair_common.mk

