
CC=/usr/bin/cc

CFLAGS= -std=iso9899:1999 \
	-pedantic -pedantic-errors \
	-march=rv64imafdc -mabi=lp64d -m64 -g -O0 \
	-fno-builtin -fno-fast-math -ffp-contract=off \
	-fno-color-diagnostics \
	-Weverything -Wno-reserved-id-macro \
	-Wno-padded -Wno-disabled-macro-expansion \
	-Wno-sign-conversion -Wno-extra-semi-stmt \
	-Wno-reserved-identifier -Wno-unused-macros \
	-Wno-strict-prototypes -Wno-unsafe-buffer-usage

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_XOPEN_SOURCE=600

LDIR=	/opt/bw/lib
IDIR=	/opt/bw/include
ITIME=	../time_and_date

LIBS=	-lgmp -lmpfr

SRCS = ../sysinfo/sysinfo.c ../sysinfo/endian.c \
	../time_and_date/tdiff.c gmp_mpfr_ver.c fred.c

OBJS = ../sysinfo/sysinfo.o ../sysinfo/endian.o \
	../time_and_date/tdiff.o gmp_mpfr_ver.o fred.o

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) -I$(IDIR) -I$(ITIME) $(CPPFLAGS)

fred: $(OBJS)
	$(CC) -o $@ $(OBJS) $(CFLAGS) -Wl,-rpath=$(LDIR) -Wl,-enable-new-dtags $(CPPFLAGS) -L$(LDIR) $(LIBS)

clean:
	rm -f $(OBJS) fred
