
CC=/usr/bin/gcc

CFLAGS= -I$(IDIR) -std=iso9899:1999 -pedantic -fno-builtin -g -m64 \
	-Wl,-rpath=/opt/bw/lib,--enable-new-dtags \
	-mcpu=970 -mno-altivec -mno-isel -mno-vsx \
	-mno-crypto -mno-htm -mno-quad-memory-atomic -mfull-toc \
	-mno-multiple -mupdate -mno-avoid-indexed-addresses \
	-ffp-contract=off -mno-mulhw \
	-mno-dlmzb -mno-bit-align -mno-strict-align -mbig -mregnames \
	-mno-recip -fno-unsafe-math-optimizations

CPPFLAGS= -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

IDIR=/opt/bw/include
LDIR=/opt/bw/lib

LIBS = -lm -lgmp -lmpfr

SRC = mpfr_ver.c \
	../time_and_date/timediff.c \
	../sysinfo/sysinfo.c \
   	../sysinfo/sysmem.c

OBJ = mpfr_ver.o \
	  ../time_and_date/timediff.o \
	  ../sysinfo/sysinfo.o \
	  ../sysinfo/sysmem.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS) -I$(IDIR)

mpfr_ver: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) -L$(LDIR) $(LIBS)

clean:
	rm -f $(OBJ) mpfr_ver.o mpfr_ver pi*
