
CC=/usr/bin/gcc

CFLAGS= -g -m64 -std=iso9899:1999 -pedantic -fno-builtin -O0 \
	-mcpu=power9 -mno-isel -mno-crypto -mno-htm -mno-quad-memory-atomic \
	-mfloat128-hardware -mfull-toc -mno-multiple -mupdate \
	-mno-avoid-indexed-addresses -mno-toc -mregnames -mno-recip \
	-fno-unsafe-math-optimizations

CPPFLAGS=-D_TS_ERRNO -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

LIBS = -lm -lgmp -lmpfr

IDIR=/opt/bw/include
LDIR=/opt/bw/lib

SRC = mpfr_ver.c ../time_and_date/timediff.c ../sysinfo/sysinfo.c
OBJ = mpfr_ver.o ../time_and_date/timediff.o ../sysinfo/sysinfo.o

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) -I$(IDIR) $(CPPFLAGS)

mpfr_ver: $(OBJ)
	$(CC) -o $@ $(OBJ) $(CFLAGS) -Wl,-rpath=$(LDIR),--enable-new-dtags $(CPPFLAGS) -L$(LDIR) $(LIBS)

clean:
	rm -f $(OBJ) mpfr_ver
