
CC=/usr/bin/cc

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_XOPEN_SOURCE=600

CFLAGS= -std=iso9899:1999 -pedantic -pedantic-errors -m64 -g -O0 \
	-fno-fast-math -fno-builtin -fno-color-diagnostics \
	-Wno-reserved-id-macro -Wno-missing-prototypes \
	-Wno-padded -Wno-disabled-macro-expansion -Wno-sign-conversion \
	-Wno-reserved-identifier -Wno-extra-semi-stmt \
	-Wno-unsafe-buffer-usage -Wno-cast-function-type-strict

LIBS=	-lgmp -lm

include pair_common.mk

