
CC=/usr/bin/gcc

CFLAGS= -m64 -O3 -march=native -mpc80 -malign-double \
	-m128bit-long-double -mlong-double-80 \
	-mstackrealign -mpreferred-stack-boundary=4

CPPFLAGS=-D_TS_ERRNO -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

LIBS = -lm -lgmp -lmpfr

SRC = mpfr_ver.c ../time_and_date/timediff.c ../sysinfo/sysinfo.c
OBJ = mpfr_ver.o ../time_and_date/timediff.o ../sysinfo/sysinfo.o

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

mpfr_ver: $(OBJ)
	$(CC) -o $@ $(OBJ) $(CFLAGS) $(CPPFLAGS) $(LIBS)

clean:
	rm -f $(OBJ) mpfr_ver
