
CC=/usr/bin/gcc

CFLAGS= -std=iso9899:1999 -m64 -g -O0 -fno-builtin \
	-march=k8 -mtune=k8 -mieee-fp -mhard-float -mpc80 \
	-fno-fast-math -malign-double \
	-m128bit-long-double -mlong-double-80 \
	-mstackrealign -mpreferred-stack-boundary=4 -mno-mmx \
    -Wl,-rpath=/opt/bw/lib,--enable-new-dtags

CPPFLAGS=-D_TS_ERRNO -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

IDIR=/opt/bw/include
LDIR=/opt/bw/lib

LIBS = -lm -lgmp -lmpfr

SRC = mpfr_ver.c ../time_and_date/timediff.c ../sysinfo/sysinfo.c
OBJ = mpfr_ver.o ../time_and_date/timediff.o ../sysinfo/sysinfo.o

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) -I$(IDIR) $(CPPFLAGS)

mpfr_ver: $(OBJ)
	$(CC) -o $@ $(OBJ) $(CFLAGS) -Wl,-rpath,$(LDIR) $(CPPFLAGS) -L$(LDIR) $(LIBS)

clean:
	rm -f $(OBJ) mpfr_ver
