
CC?= /usr/bin/gcc

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_XOPEN_SOURCE=600

CFLAGS= -std=iso9899:1999 -pedantic -fno-builtin -g -m64 \
	-Wl,-rpath=/opt/bw/lib,--enable-new-dtags \
	-mcpu=970 -mno-altivec -mno-isel -mno-vsx \
	-mno-crypto -mno-htm -mno-quad-memory-atomic -mfull-toc \
	-mno-multiple -mupdate -mno-avoid-indexed-addresses \
	-ffp-contract=off -mno-mulhw \
	-mno-dlmzb -mno-bit-align -mno-strict-align -mbig -mregnames \
	-mno-recip -fno-unsafe-math-optimizations

LIBS=	-lgmp -lm

include pair_common.mk

