
CC=/usr/bin/cc

CFLAGS= -g -O0 -m64 -fno-builtin -mcpu=power9 -mpowerpc64 \
		-mno-altivec -msecure-plt -mno-vsx -mno-quad-memory \
		-mno-float128 -mhard-float -mno-float128-hardware \
		-mno-avoid-indexed-addresses -mno-isel -mno-crypto \
		-mno-htm -mno-quad-memory-atomic -mno-multiple \
		-mupdate -mno-avoid-indexed-addresses -mregnames \
		-mno-recip -fno-unsafe-math-optimizations \
		-fno-fast-math -mbig -mno-fp-in-toc -mno-sum-in-toc \
		-ffp-contract=off \
		-Wl,-rpath=/opt/bw/lib,--enable-new-dtags

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 \
	-D_XOPEN_SOURCE=600

LIBS=	-lgmp -lmpfr -lcrypto -lm

include fg_common.mk

