
CC=/opt/bw/gcc13/bin/gcc

CFLAGS= -g -m64 -std=iso9899:1999 -pedantic -fno-builtin -O0 \
	-mcpu=power9 -mno-isel -mno-crypto -mno-htm -mno-quad-memory-atomic \
	-mfloat128-hardware -mfull-toc -mno-multiple -mupdate \
	-mno-avoid-indexed-addresses -mno-toc -mregnames -mno-recip \
	-fno-unsafe-math-optimizations

include common.mk
