
CC=/usr/bin/gcc

CFLAGS= -std=iso9899:1999 -pedantic -pedantic-errors -m64 -g -O0 \
   	-fno-builtin -mcpu=970 -mno-altivec -mno-isel -mno-vsx \
	-mno-crypto -mno-htm -mno-quad-memory-atomic -mfull-toc \
	-mno-multiple -mupdate -mno-avoid-indexed-addresses \
	-mno-dlmzb -mno-bit-align -mno-strict-align -mbig -mregnames \
	-mno-recip -fno-unsafe-math-optimizations -pedantic-errors \
	-Wall

CPPFLAGS= -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

LIBS = -lrt

SRCS = file_times.c

OBJS = file_times.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

file_times: file_times.o $(OBJS)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) $(LIBS)

clean:
	rm -f $(OBJS) file_times
