
CC=/usr/bin/gcc

CFLAGS= -std=iso9899:1999 -pedantic -pedantic-errors \
   	-m64 -O0 -g -fno-builtin \
	-march=k8 -mtune=k8 -mieee-fp -mhard-float -mpc80 \
	-fno-fast-math -malign-double \
	-m128bit-long-double \
	-mstackrealign -mpreferred-stack-boundary=4 -mno-mmx \
	-Wl,-rpath=/opt/bw/lib,--enable-new-dtags

CPPFLAGS= -D_LARGEFILE64_SOURCE

IDIR=/opt/bw/include
LDIR=/opt/bw/lib

LIBS = -lssl -lcrypto -lm

SRCS = ./dgst_test.c ../../../sysinfo/sysinfo.c \
	   ../../../sysinfo/endian.c

OBJS = ./dgst_test.o ../../../sysinfo/sysinfo.o \
	   ../../../sysinfo/endian.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS) -I$(IDIR)

dgst_test: dgst_test.o $(OBJS)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) -L$(LDIR) $(LIBS)

clean:
	rm -f $(OBJS) dgst_test

