
CC=/usr/bin/cc

CFLAGS= -std=iso9899:1999 -pedantic -pedantic-errors \
	-g -O0 -fno-builtin -fno-unsafe-math-optimizations \
	-march=rv64imafdc -mabi=lp64d \
	-Wl,-rpath=/opt/bw/lib -Wl,-enable-new-dtags

CPPFLAGS= -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

IDIR=/opt/bw/include
LDIR=/opt/bw/lib

LIBS= -lcrypto -lm

SRCS = ./dgst_test.c ../../../sysinfo/sysinfo.c \
	   ../../../sysinfo/endian.c

OBJS = ./dgst_test.o ../../../sysinfo/sysinfo.o \
	   ../../../sysinfo/endian.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS) -I$(IDIR)

dgst_test: dgst_test.o $(OBJS)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) -L$(LDIR) $(LIBS)

clean:
	rm -f $(OBJS) dgst_test

