
CC=/opt/developerstudio12.6/bin/c99

CFLAGS= -I$(IDIR) -Xc -g -errfmt=error -erroff=%none -xmemalign=8s -errshort=full \
	-xstrconst -xildoff -m64 -xnolibmil -xcode=pic32 -xregs=no%appl \
	-xlibmieee -ftrap=%none -xarch=sparc -mc -xs -xbuiltin=%none \
	-xdebugformat=dwarf -xunroll=1

CPPFLAGS=-D_TS_ERRNO -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

LIBS = -lm -lgmp
LDIR = /opt/bw/lib
IDIR = /opt/bw/include
LDFLAGS = -L/opt/bw/lib
LD_OPTIONS = -64 -R/opt/bw/lib -L/opt/bw/lib
LD_RUN_PATH = /opt/bw/lib

SRC = rw.c
OBJ = rw.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS) -I$(IDIR)

rw: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) -Wl,-rpath=$(LDIR) -L$(LDIR) $(LIBS)

clean:
	rm -f *.o rw
