
CC=/usr/bin/gcc

CFLAGS= -std=iso9899:1999 -pedantic -pedantic-errors \
	-g -O0 -fno-builtin -fno-fast-math -mlittle-endian \
	-mgnu-as -mgnu-ld -mregister-names -mno-inline-int-divide \
	-mno-inline-sqrt -ffp-contract=off -mtune=itanium2 \
	-mno-sched-br-data-spec -mno-sched-ar-data-spec \
	-mno-sched-control-spec -msched-count-spec-in-critical-path \
	-Wl,-rpath=/opt/bw/lib,--enable-new-dtags

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=600

LIBS= -lX11 -lm

include common.mk
