
CC=/usr/bin/cc

CFLAGS= -std=iso9899:1999 -pedantic -pedantic-errors \
	-g -O0 -m64 -fno-builtin -mcpu=power9 -mno-isel \
	-mno-crypto -mno-htm -mregnames \
	-fno-unsafe-math-optimizations -fno-fast-math \
	-mfull-toc -mno-fp-in-toc -mno-sum-in-toc \
	-ffp-contract=off \
	-Wl,-rpath=/opt/bw/lib,--enable-new-dtags

CPPFLAGS= -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

IDIR=/opt/bw/include
LDIR=/opt/bw/lib

LIBS = -lssl -lcrypto -lm

SRCS = ./dgst_test.c ../../sysinfo/sysinfo.c \
	   ../../sysinfo/endian.c

OBJS = ./dgst_test.o ../../sysinfo/sysinfo.o \
	   ../../sysinfo/endian.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS) -I$(IDIR)

dgst_test: dgst_test.o $(OBJS)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) -L$(LDIR) $(LIBS)

clean:
	rm -f $(OBJS) dgst_test

