
CC=/opt/developerstudio12.6/bin/c99

CFLAGS= -Xc -g -errfmt=error -erroff=%none -xmemalign=8s -errshort=full \
	-xstrconst -xildoff -m64 -xnolibmil -xcode=pic32 -xregs=no%appl \
	-xlibmieee -ftrap=%none -xarch=sparc -mc -xs -xbuiltin=%none \
	-xdebugformat=dwarf -xunroll=1

CPPFLAGS= -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

IDIR=/opt/bw/include
LDIR=/opt/bw/lib
LIBS = -lm -lgmp -lmpfr

SRCS = trap_test.c mpfr_check_flags.c ../sysinfo/sysinfo.c
OBJS = trap_test.o mpfr_check_flags.o ../sysinfo/sysinfo.o

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) -I$(IDIR) $(CPPFLAGS)

trap_test: $(OBJS)
	$(CC) -o $@ $(OBJS) $(CFLAGS) $(CPPFLAGS) -L$(LDIR) $(LIBS)

clean:
	rm -f $(OBJS) trap_test
