CC=/usr/bin/cc

CFLAGS= -I$(IDIR) -std=iso9899:1999 -fno-builtin -g -march=armv7-a \
	-mtune=cortex-a17 -mfpu=vfpv4-d16 -mstructure-size-boundary=32 \
	-marm -mtls-dialect=gnu2 -pedantic -Wl,-rpath=/opt/bw/lib \
	-mno-sched-prolog -mlittle-endian

CPPFLAGS= -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=600

IDIR=/opt/bw/include
LDIR=/opt/bw/lib

LIBS = -lm -lgmp -lmpfr

SRC = chud.c mpfr_check_flags.c

OBJ = chud.o mpfr_check_flags.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS) -I$(IDIR)

chud: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) -L$(LDIR) $(LIBS)

clean:
	rm -f $(OBJ) chud.o chud mpfr_check_flags.o
