
CC=/usr/bin/cc

CFLAGS= -I$(IDIR) -std=iso9899:1999 -m64 -g -O0 -fno-builtin \
	-march=k8 -mtune=k8 -mieee-fp -mhard-float -mpc80 \
	-fno-fast-math -malign-double \
	-m128bit-long-double -mlong-double-80 \
	-mstackrealign -mpreferred-stack-boundary=4 -mno-mmx \

CPPFLAGS= -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

IDIR=/opt/bw/include
LDIR=/opt/bw/lib
LIBS = -lm -lgmp -lmpfr

SRC = chud.c mpfr_check_flags.c

OBJ = chud.o mpfr_check_flags.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS) -I$(IDIR)

chud: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) -L$(LDIR) $(LIBS)

clean:
	rm -f $(OBJ) chud.o chud mpfr_check_flags.o
