
CC=/usr/bin/cc

CFLAGS= -std=iso9899:1999 -m64 -g -O0 -pedantic -pedantic-errors \
	-march=rv64imafdc -mabi=lp64d \
	-Weverything -Wno-reserved-id-macro -Wno-unused-macros \
	-Wno-missing-prototypes -Wno-padded -fno-fast-math -fno-builtin

CPPFLAGS= -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

IDIR=/opt/bw/include
LDIR=/opt/bw/lib
LIBS=-lm -lgmp -lmpfr

SRCS = trap_test.c mpfr_check_flags.c ../sysinfo/sysinfo.c
OBJS = trap_test.o mpfr_check_flags.o ../sysinfo/sysinfo.o

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) -I$(IDIR) $(CPPFLAGS)

trap_test: $(OBJS)
	$(CC) -o $@ $(OBJS) $(CFLAGS) $(CPPFLAGS) -L$(LDIR) $(LIBS)

clean:
	rm -f $(OBJS) trap_test
