CC?=		/usr/bin/cc

CFLAGS=		-std=iso9899:1999 -m64 -g -O0 -fno-builtin \
		-fno-fast-math -pedantic -pedantic-errors

CPPFLAGS=	 -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
		-D_XOPEN_SOURCE=600

LIBS=		-lm

OBJS=		qsort.o

.PHONY: all
all: qsort

qsort: $(OBJS)
	$(CC) -o qsort $(OBJS) $(CFLAGS) $(CPPFLAGS) $(LIBS)

.PHONY: clean
clean:
	rm -f $(OBJS) qsort
