
CC=/usr/bin/cc

CFLAGS= -std=iso9899:2011 -pedantic -pedantic-errors -Weverything \
	-Wno-reserved-id-macro -Wno-missing-prototypes -m32 -g -O0 \
	-fno-fast-math -fno-builtin

CPPFLAGS= -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE

SRCS = filetimes.c ../sysinfo/sysinfo.c
OBJS = filetimes.o ../sysinfo/sysinfo.o

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

filetimes: $(OBJS)
	$(CC) -o $@ $(OBJS) $(CFLAGS) $(CPPFLAGS)

clean:
	rm -f $(OBJS) filetimes
