
CC=/usr/bin/c++

CFLAGS= -g -O0 -fno-builtin -m64 -mcpu=970 -mno-altivec -mno-isel \
	-mno-vsx -mno-crypto -mno-htm -mno-quad-memory-atomic -mfull-toc \
	-mno-multiple -mupdate -mno-avoid-indexed-addresses -mno-dlmzb \
	-mno-bit-align -mno-strict-align -mbig -mregnames -mno-recip \
	-fno-unsafe-math-optimizations -pedantic-errors -Wall

CPPFLAGS= -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE

LIBS = -lpng -lglfw -lGLEW -lGL -lGLU

SRCS = ./canvas.cc ./geometry.cc ./furtexture.cc ./shader.cc ./texture.cc

OBJS = ./canvas.o ./geometry.o ./furtexture.o ./shader.o ./texture.o

.cc.o:
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

grass: $(OBJS)
	$(CC) -o $@ $(OBJS) $(CFLAGS) $(CPPFLAGS) $(LIBS)

clean:
	rm -f $(OBJS) grass.o grass
