
CC=/usr/pkg/gcc10/bin/gcc

CFLAGS= -m64 -g -O0 \
	-fno-builtin -fno-fast-math -mhard-float -mno-app-regs \
   	-mcpu=ultrasparc

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=600

IDIR=/usr/pkg/include -I/usr/X11R7/include
LDIR=/usr/pkg/lib -L/usr/X11R7/lib
LIBS= -lm

OBJS= fp64_wrong.o

.PHONY: all
all: fp64_wrong

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS) -I$(IDIR)

fp64_wrong: fp64_wrong.o $(OBJS)
	$(CC) -o fp64_wrong fp64_wrong.o $(OBJS) $(CFLAGS) -Wl,-rpath=$(LDIR),-enable-new-dtags $(CPPFLAGS) -L$(LDIR) $(LIBS)

.PHONY: clean
clean:
	rm -f $(OBJS) fp64_wrong.o fp64_wrong

