
CC=/usr/bin/cc

CFLAGS= -I$(IDIR) -std=iso9899:1999 -m64 -g -O0 \
	-fno-fast-math -fno-builtin -malign-double \
	-march=k8 -mtune=k8 -mieee-fp -mhard-float -mpc80 \
	-mno-fancy-math-387 -m128bit-long-double \
	-mlong-double-80 -mstackrealign \
	-mpreferred-stack-boundary=8 -mno-mmx

CPPFLAGS=-D_TS_ERRNO -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

LIBS = -lm

SRC = fp64_inexact.c
OBJ = fp64_inexact.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

fp64_inexact: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) $(LIBS)

clean:
	rm -f $(OBJ) fp64_inexact
