
CC=/usr/bin/gcc

CFLAGS= -g -m64 -std=iso9899:1999 -pedantic -fno-builtin -O0 \
	-mcpu=power9 -mno-isel -mno-crypto -mno-htm -mno-quad-memory-atomic \
	-mfloat128-hardware -mfull-toc -mno-multiple -mupdate \
	-mno-avoid-indexed-addresses -mno-toc -mregnames -mno-recip \
	-fno-unsafe-math-optimizations -fno-fast-math

CPPFLAGS=-D_TS_ERRNO -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

LIBS = -lm

SRC = fp64_inexact.c
OBJ = fp64_inexact.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

fp64_inexact: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) $(LIBS)

clean:
	rm -f $(OBJ) fp64_inexact
