
CC=/usr/bin/cc

CFLAGS= -std=iso9899:1999 -pedantic -pedantic-errors -m64 -g -O0 \
	-Weverything -Wno-reserved-identifier -Wno-reserved-id-macro \
	-fno-fast-math -fno-builtin -fsanitize=address

include common.mk
