
CC?=/usr/bin/cc

# see https://gcc.gnu.org/onlinedocs/gcc-14.2.0/gcc/x86-Options.html
#
# Warning: if you use the -malign-double switch, structures containing
# the above types are aligned differently than the published
# application binary interface specifications for the x86-32 and are
# not binary compatible with structures in code compiled without that
# switch. 
#
CFLAGS= -std=iso9899:1999 -pedantic -pedantic-errors -m64 -g -O0 \
	-fno-builtin -fno-fast-math -march=k8 -mtune=k8 -mieee-fp \
	-mhard-float -mlong-double-128 -m128bit-long-double \
	-mstackrealign -mpreferred-stack-boundary=8 -fPIC

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 \
			-D_XOPEN_SOURCE=600

LIBS= -lX11 -lm

include common.mk
