
CC=/usr/bin/cc

CFLAGS= -std=iso9899:1999 -pedantic -pedantic-errors -Weverything \
	-m32 -g -O0 -fno-builtin -fno-fast-math -pedantic \
	-pedantic-errors -Weverything -Wno-reserved-id-macro \
	-Wno-double-promotion -Wno-implicit-float-conversion \
	-Wno-missing-prototypes -Wno-reserved-identifier \
	-Wno-documentation -Wno-unsafe-buffer-usage \
	-Wno-unused-variable

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=600

LIBS= -lX11 -lm

include common.mk
