
CC=/usr/bin/gcc-9

CFLAGS= -I$(IDIR) -std=iso9899:1999 -m32 -g -O0 \
	-march=i686 -mtune=i686 -Wl,-rpath=/opt/bw/lib,--enable-new-dtags \
	-fno-builtin -malign-double -mpc80 -mno-mmx -mno-sse -mno-sse2 \
	-mno-sse3 -mno-ssse3 -mno-sse4 -mno-sse4a -mno-sse4.1 -mno-sse4.2 \
	-mno-avx -mno-avx2 -mno-avx512f -mno-avx512pf -mno-avx512er \
	-mno-avx512cd -mno-avx512vl -mno-avx512bw -mno-avx512dq \
	-mno-avx512ifma -mno-avx512vbmi -mno-sha -mno-aes -mno-pclmul \
	-mno-clflushopt -mno-clwb -mno-fsgsbase -mno-rdrnd -mno-f16c \
	-mno-fma -mno-pconfig -mno-wbnoinvd -mno-fma4 -mno-prfchw \
	-mno-rdpid -mno-prefetchwt1 -mno-rdseed -mno-sgx -mno-xop \
	-mno-lwp -mno-3dnow -mno-3dnowa -mno-popcnt -mno-abm -mno-adx \
	-mno-bmi -mno-bmi2 -mno-lzcnt -mno-fxsr -mno-xsave -mno-xsaveopt \
	-mno-xsavec -mno-xsaves -mno-rtm -mno-hle -mno-tbm -mno-mpx \
	-mno-mwaitx -mno-clzero -mno-pku -mno-avx512vbmi2 -mno-gfni \
	-mno-vaes -mno-vpclmulqdq -mno-avx512bitalg -mno-movdiri \
	-mno-movdir64b -mno-avx512vpopcntdq -mno-avx5124fmaps \
	-mno-avx512vnni -mno-avx5124vnniw

CPPFLAGS= -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

LIBS = -lX11 -lrt -lm

CMPLEX_DIR=../complex_vector
IDIR=/usr/local/include
LDIR=/usr/local/lib

SRCS = xray.c \
	../xwin/x_error_handler.c \
	../xwin/create_gc.c \
	../xwin/create_borderless_topwin.c \
	../time_and_date/timediff.c \
	../complex_vector/icept.c \
	../complex_vector/surface_icept_pt.c \
	../complex_vector/gradient.c \
	../complex_vector/cplex_add.c \
	../complex_vector/cplex_check.c \
	../complex_vector/cplex_div.c \
	../complex_vector/cplex_mag.c \
	../complex_vector/cplex_mult.c \
	../complex_vector/cplex_quad.c \
	../complex_vector/cplex_sq.c \
	../complex_vector/cplex_sqrt.c \
	../complex_vector/cplex_sub.c \
	../complex_vector/cplex_theta.c \
	../complex_vector/cplex_vec_add.c \
	../complex_vector/cplex_vec_copy.c \
	../complex_vector/cplex_vec_dot.c \
	../complex_vector/cplex_vec_set.c \
	../complex_vector/cplex_vec_print.c \
	../complex_vector/cplex_vec_scale.c \
	../complex_vector/cplex_vec_mag.c \
	../complex_vector/cplex_vec_normalize.c \
	../complex_vector/cplex_vec_cross.c \
	../complex_vector/cplex_cramer.c \
	../complex_vector/cplex_det.c \
	../complex_vector/line_plane_icept.c \
	../complex_vector/cplex_vec_check.c \
	../sysinfo/sysinfo.c


OBJS = ../xwin/x_error_handler.o \
	../xwin/create_gc.o \
	../xwin/create_borderless_topwin.o \
	../time_and_date/timediff.o \
	../complex_vector/icept.o \
	../complex_vector/surface_icept_pt.o \
	../complex_vector/gradient.o \
	../complex_vector/cplex_add.o \
	../complex_vector/cplex_check.o \
	../complex_vector/cplex_div.o \
	../complex_vector/cplex_mag.o \
	../complex_vector/cplex_mult.o \
	../complex_vector/cplex_quad.o \
	../complex_vector/cplex_sq.o \
	../complex_vector/cplex_sqrt.o \
	../complex_vector/cplex_sub.o \
	../complex_vector/cplex_theta.o \
	../complex_vector/cplex_vec_add.o \
	../complex_vector/cplex_vec_copy.o \
	../complex_vector/cplex_vec_dot.o \
	../complex_vector/cplex_vec_set.o \
	../complex_vector/cplex_vec_print.o \
	../complex_vector/cplex_vec_scale.o \
	../complex_vector/cplex_vec_mag.o \
	../complex_vector/cplex_vec_normalize.o \
	../complex_vector/cplex_vec_cross.o \
	../complex_vector/cplex_cramer.o \
	../complex_vector/cplex_det.o \
	../complex_vector/line_plane_icept.o \
	../complex_vector/cplex_vec_check.o \
	../sysinfo/sysinfo.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS) -I$(CMPLEX_DIR) -I$(IDIR)

xray: xray.o $(OBJS)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) -L$(LDIR) $(LIBS)

clean:
	rm -f $(OBJS) xray.o xray
