
CC=/usr/bin/gcc

CFLAGS= -std=iso9899:1999 -m64 -g -O0 -pedantic -pedantic-errors \
	-fno-builtin -fno-fast-math -mhard-float -mno-app-regs -mflat \
	-msoft-quad-float -mno-unaligned-doubles -mno-faster-structs \
	-mcpu=niagara7 -mtune=niagara7 -mno-vis -mno-cbcond \
	-mno-fmaf -mno-fsmuld -mno-popc -mno-subxc

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=600 \
	-D_FILE_OFFSET_BITS=64

LIBS = -lgmp -lmpfr

SRCS = ./pollard_rho.c ../gmp_mpfr/gmp_mpfr_ver.c \
	../gmp_mpfr/mpfr_check_flags.c \
	../gmp_mpfr/gcd_mpfr.c \
	../time_and_date/tdiff.c


OBJS = ./pollard_rho.o ../gmp_mpfr/gmp_mpfr_ver.o \
	../gmp_mpfr/mpfr_check_flags.o \
	../gmp_mpfr/gcd_mpfr.o \
	../time_and_date/tdiff.o

%.o: %.c
	$(CC) -I../time_and_date -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

pollard_rho: pollard_rho.o $(OBJS)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) $(LIBS)

clean:
	rm -f $(OBJS) pollard_rho.o pollard_rho

