
CC=/opt/bw/gcc12/bin/gcc

CFLAGS= -I$(IDIR) -std=iso9899:1999 -m64 -g -O0 -fno-builtin \
	-Wl,-rpath=/opt/bw/lib,--enable-new-dtags \
	-march=k8 -mtune=k8 -mieee-fp -mhard-float -mpc80 \
	-fno-fast-math -malign-double \
	-m128bit-long-double -mlong-double-80 \
	-mstackrealign -mpreferred-stack-boundary=4 -mno-mmx \

LDIR= /opt/bw/lib
IDIR= /opt/bw/include
LIBS= -lm -lgmp -lmpfr

include common.mk
