
CC?=/usr/bin/gcc
LDIR?=/opt/bw/lib
IDIR?=/opt/bw/include

CFLAGS= -I$(IDIR) -std=iso9899:1999 -pedantic -pedantic-errors \
	-m64 -g -O0 -fno-builtin \
	-march=k8 -mtune=k8 -mieee-fp -mhard-float \
	-fno-fast-math -malign-double \
	-m128bit-long-double \
	-mstackrealign -mpreferred-stack-boundary=8 -mno-mmx \
	-Wl,-rpath=$(LDIR),--enable-new-dtags

LIBS= -lm -lgmp -lmpfr

include common.mk
