
CC=/opt/gcc/imed/gcc12/bin/gcc

CFLAGS= -I$(IDIR) -std=iso9899:1999 -fno-builtin -march=armv7-a \
	-mtune=cortex-a17 -mfpu=vfpv4-d16 \
	-marm -mtls-dialect=gnu2 -pedantic \
	-mno-sched-prolog -mlittle-endian -O0 -g \
	-Wl,-rpath=/opt/bw/lib,--enable-new-dtags

LDIR= /opt/bw/lib
IDIR= /opt/bw/include
LIBS= -lm -lgmp -lmpfr

include common.mk
