
CFLAGS= -std=iso9899:1999 -pedantic -pedantic-errors -Weverything \
	-march=rv64imafdc -mabi=lp64d \
	-Wno-reserved-id-macro -Wno-missing-prototypes -m64 -g -O0 \
	-fno-fast-math -fno-builtin

include common.mk

