
CC=/usr/bin/gcc

CFLAGS= -std=iso9899:1999 -g -O0 -fno-builtin -fno-fast-math \
		-mlittle-endian -mgnu-as -mgnu-ld -mregister-names \
		-mno-inline-int-divide -mno-inline-sqrt \
		-ffp-contract=off -mtune=itanium2 \
		-mno-sched-br-data-spec -mno-sched-ar-data-spec \
		-mno-sched-control-spec \
		-msched-count-spec-in-critical-path

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=600 \
	-D_FILE_OFFSET_BITS=64

LIBS = -lgmp -lmpfr

SRCS = ./pollard_rho.c ../gmp_mpfr/gmp_mpfr_ver.c \
	../gmp_mpfr/mpfr_check_flags.c \
	../gmp_mpfr/gcd_mpfr.c \
	../time_and_date/tdiff.c


OBJS = ./pollard_rho.o ../gmp_mpfr/gmp_mpfr_ver.o \
	../gmp_mpfr/mpfr_check_flags.o \
	../gmp_mpfr/gcd_mpfr.o \
	../time_and_date/tdiff.o

%.o: %.c
	$(CC) -I../time_and_date -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

pollard_rho: pollard_rho.o $(OBJS)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) $(LIBS)

clean:
	rm -f $(OBJS) pollard_rho.o pollard_rho

