
IDIR = .

CC?=/usr/bin/gcc

CFLAGS= -std=iso9899:1999 -pedantic -pedantic-errors \
	-m64 -g -O0 -fno-builtin -march=k8 -mtune=k8 \
	-mieee-fp -mhard-float -fno-fast-math \
	-mno-fancy-math-387 -m128bit-long-double \
	-mstackrealign -mpreferred-stack-boundary=8 -mno-mmx \
	-I$(IDIR)

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=600

DEPS = v.h

LIBS = -lm

SRCS = $(wildcard c*.c) line_plane_icept.c
OBJS = $(SRCS:.c=.o)

%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

cplex_test: $(OBJS)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) $(LIBS)

clean:
	rm -f $(OBJS) cplex_test
