
CC=	/usr/bin/cc

CPPFLAGS=	-D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=600

CFLAGS= -std=iso9899:1999 -pedantic -pedantic-errors \
	-march=rv64imafdc -mabi=lp64d \
	-fno-fast-math -fno-builtin \
	-m64 -g -O0 \
	-Weverything -Wno-reserved-id-macro -Wno-missing-prototypes \
	-Wno-reserved-identifier -Wno-unsafe-buffer-usage

include common.mk
