
CC=/usr/bin/cc

CFLAGS= -std=iso9899:1999 -pedantic -pedantic-errors -m64 -g -O0 \
	-Weverything -Wno-reserved-id-macro -Wno-missing-prototypes \
	-Wno-padded -fno-fast-math -fno-builtin

include common.mk
