
CC=/usr/bin/cc

CFLAGS= -I$(IDIR) -std=iso9899:1999 -m64 -g -O0 -fno-builtin -march=k8 \
	-mtune=k8 -mieee-fp -mhard-float -mpc80 -fno-fast-math \
	-mno-fancy-math-387 -malign-double -m128bit-long-double \
	-mlong-double-80 -mstackrealign -mpreferred-stack-boundary=8 -mno-mmx

CPPFLAGS=-D_TS_ERRNO -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

SRCS = $(wildcard b*.c)
OBJS = $(SRCS:.c=.o)

%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

bsort: $(OBJS)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS)

clean:
	rm -f $(OBJS) bsort
