
CC=/usr/bin/cc

CFLAGS= -std=iso9899:1999 -pedantic -pedantic-errors \
	-m64 -g -O0 \
	-fno-fast-math -fno-builtin -fno-unsafe-math-optimizations \
	-Weverything -Wno-unsafe-buffer-usage -Wno-reserved-identifier

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 \
	-D_XOPEN_SOURCE=600

LDIR=/usr/local/lib
IDIR=/usr/local/include

SRCS = argv_dump.c bin_printf.c ../sysinfo/sysinfo.c
OBJS = argv_dump.o bin_printf.o ../sysinfo/sysinfo.o

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) -I$(IDIR) $(CPPFLAGS)

argv_dump: $(OBJS)
	$(CC) -o $@ $(OBJS) $(CFLAGS) $(CPPFLAGS) -L$(LDIR) $(LIBS)

clean:
	rm -f $(OBJS) argv_dump
