
CC=/usr/bin/cc

CFLAGS= -std=iso9899:1999 -pedantic -pedantic-errors -Weverything \
	-Wno-reserved-id-macro -Wno-missing-prototypes -m64 -g -O0 \
	-fno-fast-math -fno-builtin

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=600

LDIR=/usr/local/lib
IDIR=/usr/local/include

SRCS = argv_dump.c bin_printf.c ../sysinfo/sysinfo.c ../sysinfo/sysmem.c
OBJS = argv_dump.o bin_printf.o ../sysinfo/sysinfo.o ../sysinfo/sysmem.o

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) -I$(IDIR) $(CPPFLAGS)

argv_dump: $(OBJS)
	$(CC) -o $@ $(OBJS) $(CFLAGS) $(CPPFLAGS) -L$(LDIR) $(LIBS)

clean:
	rm -f $(OBJS) argv_dump
