
CC = /usr/bin/gcc

CFLAGS = -std=iso9899:1999 -g -O0 -fno-builtin -fno-fast-math \
	-mlittle-endian -mgnu-as -mgnu-ld -mregister-names \
	-mno-inline-int-divide -mno-inline-sqrt -ffp-contract=off \
	-mtune=itanium2 -mno-sched-br-data-spec \
	-mno-sched-ar-data-spec -mno-sched-control-spec \
	-msched-count-spec-in-critical-path

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=500

SRCS = date_list.c print_date.c valid_date.c

OBJS = date_list.o print_date.o valid_date.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

date_list: $(OBJS)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS)

clean:
	rm -f $(OBJS) date_list
