
CC=/opt/developerstudio12.6/bin/cc

CFLAGS= -std=iso9899:1990 -m64 -xarch=sparc -g -xO0 -mc -xs \
	-errfmt=error -erroff=%none -errshort=full -errtags=yes \
	-errwarn=%none -ftrap=%none -xbuiltin=%none -xildoff \
	-xlibmieee -xstrconst -xcode=pic32 -xmemalign=8s \
	-xnolibmil -xunroll=1 -xdepend=no -xregs=no%appl \
	-xdebugformat=dwarf

CPPFLAGS= -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=500

SRCS = date_list.c print_date.c valid_date.c

OBJS = date_list.o print_date.o valid_date.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

date_list: $(OBJS)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS)

clean:
	rm -f $(OBJS) date_list
