
CC=/usr/bin/gcc

CFLAGS= -std=iso9899:1990 -pedantic -pedantic-errors -g -O0 \
	-march=rv64imafdc -mabi=lp64d -fno-builtin -fno-fast-math \
	-ffp-contract=off -fno-unsafe-math-optimizations \
	-mpreferred-stack-boundary=4

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 \
	-D_XOPEN_SOURCE=500

include common.mk

