CC=/opt/developerstudio12.6/bin/cc

CFLAGS= -Xc -m64 -xarch=sparc -g -xO0 -mc -xs \
	-errfmt=error -erroff=%none -errshort=full -errtags=yes \
	-errwarn=%none -ftrap=%none -xbuiltin=%none -xildoff \
	-xlibmieee -xstrconst -xcode=pic32 -xmemalign=8s \
	-xnolibmil -xunroll=1 -xdepend -xregs=no%appl \
	-xdebugformat=dwarf

CPPFLAGS= -D_TS_ERRNO -D_XOPEN_SOURCE=600 -D_LARGEFILE64_SOURCE \
	-D_FILE_OFFSET_BITS=64

include common.mk

