
CC?=/usr/bin/gcc

CFLAGS=	-std=iso9899:1999 -pedantic -pedantic-errors \
	-g -O0 -fno-builtin -m64 \
	-mcpu=power9 -mno-altivec -mno-isel -mno-vsx \
	-mno-crypto -mno-htm \
	-fno-unsafe-math-optimizations -Wall \
	-Wno-unsafe-buffer-usage -Wno-reserved-identifier \
	-Wpedantic

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 \
	-D_XOPEN_SOURCE=500

include trivial.mk

