
CC=/opt/developerstudio12.6/bin/c99

CFLAGS= -Xc -xmemalign=8s -m64 -xcode=pic32 \
	-xregs=no%appl -xlibmieee -mc -xs -xO3 -fast \
	-fma=fused

LDIR=/opt/bw/lib
IDIR=/opt/bw/include
RPATH=/opt/bw/lib

include common.mk
