CFLAGS=		-I$(IDIR) -std=iso9899:1999 -pedantic -g -O0 -fno-builtin -m64 \
		-mcpu=970 -mcall-freebsd -mno-altivec -mno-isel -mno-vsx \
		-mno-crypto -mno-htm -mno-quad-memory-atomic -mfull-toc \
		-mno-multiple -mupdate -mno-avoid-indexed-addresses \
		-mno-dlmzb -mno-bit-align -mno-strict-align -mbig -mregnames \
		-mno-recip -fno-unsafe-math-optimizations -pedantic-errors \
		-Wall

.include "fbsd_common.mk"
