
CC=/usr/bin/cc

CFLAGS= -I$(IDIR) -std=iso9899:1999 -m64 -O3 \
	-Wl,-rpath=/opt/bw/lib,--enable-new-dtags \
	-mstackrealign -mpreferred-stack-boundary=4 \
	-ffp-contract=on

CPPFLAGS= -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

IDIR=/opt/bw/include
LDIR=/opt/bw/lib
LD_OPTIONS=-L/opt/bw/lib
LD_RUN_PATH=/opt/bw/lib

LIBS = -lX11 -lrt -lm -lpthread

SRCS = ./mandel_col.c ./linear_inter.c ./mbrot.c \
	./mbrot.c ./mbrot_vbox_pthread.c \
	../xwin/x_error_handler.c \
	../xwin/create_gc.c \
	../xwin/create_borderless_topwin.c \
	../time_and_date/timediff.c \
	../sysinfo/sysmem.c ../sysinfo/sysinfo.c


OBJS = ./mandel_col.o ./linear_inter.o ./mbrot.o \
	./mbrot.o ./mbrot_vbox_pthread.o \
	../xwin/x_error_handler.o \
	../xwin/create_gc.o \
	../xwin/create_borderless_topwin.o \
	../time_and_date/timediff.o \
	../sysinfo/sysmem.o ../sysinfo/sysinfo.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

xmand: xmand.o $(OBJS)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) $(LIBS)

clean:
	rm -f $(OBJS) xmand.o xmand
