
CC=/usr/bin/gcc

CFLAGS= -I$(IDIR) -std=iso9899:1999 -m32 -O3 -pedantic \
	-pedantic-errors -Wall -Wl,-rpath=/opt/bw/lib,--enable-new-dtags \
	-malign-double -mpc80

CPPFLAGS=-D_TS_ERRNO -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

LIBS = -lX11 -lrt -lm -lpthread

LDIR=/usr/local/lib
IDIR=/usr/local/include

SRCS = ./mandel_col.c ./linear_inter.c ./mbrot.c \
	./mbrot.c ./mbrot_vbox_pthread.c \
	../xwin/x_error_handler.c \
	../xwin/create_gc.c \
	../xwin/create_borderless_topwin.c \
	../time_and_date/timediff.c \
	../sysinfo/sysmem.c ../sysinfo/sysinfo.c \
	../sysinfo/ru.c

OBJS = ./mandel_col.o ./linear_inter.o \
	./mbrot.o ./mbrot_vbox_pthread.o \
	../xwin/x_error_handler.o \
	../xwin/create_gc.o \
	../xwin/create_borderless_topwin.o \
	../time_and_date/timediff.o \
	../sysinfo/sysmem.o ../sysinfo/sysinfo.o \
	../sysinfo/ru.o

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) -I$(IDIR)  $(CPPFLAGS)

xmand: xmand.o $(OBJS)
	$(CC) -o $@ xmand.o $(OBJS) $(CFLAGS) $(CPPFLAGS) -L$(LDIR) $(LIBS)

clean:
	rm -f $(OBJS) xmand.o xmand
