
CC=/opt/developerstudio12.6/bin/c99

CFLAGS= -I$(IDIR) -Xc -xmemalign=8s -m64 -xcode=pic32 \
	-xregs=no%appl -xlibmieee -mc -xs -xO3 -fast \
	-fma=fused

CPPFLAGS= -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

LIBS = -lX11 -lrt -lm -lpthread
LDIR=/opt/bw/lib
IDIR=/opt/bw/include
RPATH=/opt/bw/lib

SRCS = mandel_col.c linear_inter.c mbrot.c \
	mbrot_vbox_pthread.c \
	fp_region.c fp_translate.c fp_vbox.c \
	array_offset.c \
	../xwin/x_error_handler.c \
	../xwin/create_gc.c \
	../xwin/create_borderless_topwin.c \
	../time_and_date/timediff.c \
	../in_progress/data_dump/rot4.c \
	../in_progress/data_dump/rot8.c \
	../sysinfo/sysinfo.c

OBJS = mandel_col.o linear_inter.o mbrot.o \
	mbrot_vbox_pthread.o \
	fp_region.o fp_translate.o fp_vbox.o \
	array_offset.o \
	../xwin/x_error_handler.o \
	../xwin/create_gc.o \
	../xwin/create_borderless_topwin.o \
	../time_and_date/timediff.o \
	../in_progress/data_dump/rot4.o \
	../in_progress/data_dump/rot8.o \
	../sysinfo/sysinfo.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS) -I. -I$(IDIR)

xmand: xmand.o $(OBJS)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) -L$(LDIR) -R$(RPATH) $(LIBS)

clean:
	rm -f $(OBJS) xmand.o xmand

