
CC=/usr/bin/cc

CFLAGS= -std=iso9899:2011 -m64 -O3 -mhard-float -mno-app-regs -mflat \
	-msoft-quad-float -mcpu=ultrasparc -mtune=ultrasparc -mno-vis \
	-mcmodel=medany -mmemory-model=tso -fPIC -Wl,-rpath=/usr/lib64 \
	-Wl,-rpath=/usr/lib64 -Wl,-pie

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=600

IDIR=/usr/include -I/usr/include/X11
LDIR=/usr/lib64 -L/usr/lib64
LIBS=-lX11 -lrt -lm -lpthread

include common.mk

