
CC = /usr/bin/gcc

CFLAGS = -std=iso9899:1999 -g -O0 -m64 -fno-builtin -mcpu=970 \
	-mpowerpc64 -mno-altivec -msecure-plt -mno-vsx \
	-mno-quad-memory -mno-float128 -mhard-float \
	-mno-float128-hardware -mno-avoid-indexed-addresses \
	-mno-isel -mno-crypto -mno-htm -mno-quad-memory-atomic \
	-mno-multiple -mupdate -mno-avoid-indexed-addresses \
	-mregnames -mno-recip -fno-unsafe-math-optimizations \
	-fno-fast-math -mbig -mno-fp-in-toc -mno-sum-in-toc \
	-ffp-contract=fast \
	-Wl,-rpath=/opt/bw/lib,--enable-new-dtags

include common.mk

