
CC=/usr/bin/gcc

CFLAGS= -g -m64 -std=iso9899:1999 -pedantic -fno-builtin -O0 \
	-mcpu=power9 -mno-isel -mno-crypto -mno-htm -mno-quad-memory-atomic \
	-mfloat128-hardware -mfull-toc -mno-multiple -mupdate \
	-mno-avoid-indexed-addresses -mno-toc -mregnames -mno-recip \
	-fno-unsafe-math-optimizations

CPPFLAGS=-D_TS_ERRNO -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

LIBS = -lX11 -lrt -lm -lpthread

LDIR=/usr/local/lib
IDIR=/usr/local/include

SRCS = ./mandel_col.c \
	./linear_inter.c \
	./mbrot.c \
	../xwin/x_error_handler.c \
	../xwin/create_gc.c \
	../xwin/create_borderless_topwin.c \
	../time_and_date/timediff.c \
	../pthread/sysmem.c ../pthread/sysinfo.c


OBJS = ./mandel_col.o \
	./linear_inter.o \
	./mbrot.o \
	../xwin/x_error_handler.o \
	../xwin/create_gc.o \
	../xwin/create_borderless_topwin.o \
	../time_and_date/timediff.o \
	../pthread/sysmem.o ../pthread/sysinfo.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS) -I$(IDIR)

xmand: xmand.o $(OBJS)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) -L$(LDIR) $(LIBS)

clean:
	rm -f $(OBJS) xmand.o xmand
