
CC=/usr/bin/cc

IDIR = ../read_dump -I../../pthread

CFLAGS= -I$(IDIR) -std=iso9899:1999 -fno-builtin -march=armv7-a \
        -mtune=cortex-a17 -mfpu=vfpv4-d16 -marm \
        -mtls-dialect=gnu2 -pedantic -Wl,-rpath=/opt/bw/lib \
        -mno-sched-prolog -mlittle-endian -O0 -g

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=600

include common.mk
