
CC=/usr/bin/gcc

CFLAGS= -I$(IDIR) -std=iso9899:1999 -m64 -g -O0 -pedantic \
	-pedantic-errors -fno-builtin -fno-fast-math -mhard-float \
	-mno-app-regs -mflat -mhard-quad-float \
	-mno-unaligned-doubles -mno-faster-structs \
	-mcpu=ultrasparc -mtune=ultrasparc -mno-vis -mno-cbcond \
	-mno-fmaf -mno-fsmuld -mno-popc -mno-subxc -mcmodel=medany \
	-mmemory-model=tso

CPPFLAGS= -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

LDIR=/usr/local/lib
IDIR=/usr/local/include
LIBS= -lm

SRCS = mandelbrot.c parse_double.c ../sysinfo/sysinfo.c ../sysinfo/sysmem.c
OBJS = mandelbrot.o parse_double.o ../sysinfo/sysinfo.o ../sysinfo/sysmem.o

.c.o:
	$(CC) -c -o $@ $< $(CFLAGS) -I$(IDIR) -I../pthread $(CPPFLAGS)

mandelbrot: $(OBJS)
	$(CC) -o $@ $(OBJS) $(CFLAGS) $(CPPFLAGS) -L$(LDIR) $(LIBS)

clean:
	rm -f $(OBJS) mandelbrot
