
CC=/opt/developerstudio12.6/bin/c99

CFLAGS= -I$(IDIR) -Xc -g -errfmt=error -erroff=%none -xmemalign=8s -errshort=full \
		-xstrconst -xildoff -m64 -xnolibmil -xcode=pic32 -xregs=no%appl \
		-xlibmieee -ftrap=%none -xarch=sparc -mc -xs -xbuiltin=%none \
		-xdebugformat=dwarf -xunroll=1

CPPFLAGS=-D_TS_ERRNO -D_POSIX_PTHREAD_SEMANTICS -D_LARGEFILE64_SOURCE \
	-D_XOPEN_SOURCE=600

LIBS = -lm

IDIR=../complex_vector

SRCS = obs_point.c \
	../complex_vector/icept.c \
	../complex_vector/surface_icept_pt.c \
	../complex_vector/gradient.c \
	../complex_vector/cplex_add.c \
	../complex_vector/cplex_check.c \
	../complex_vector/cplex_vec_check.c \
	../complex_vector/cplex_div.c \
	../complex_vector/cplex_mag.c \
	../complex_vector/cplex_mult.c \
	../complex_vector/cplex_quad.c \
	../complex_vector/cplex_sq.c \
	../complex_vector/cplex_sqrt.c \
	../complex_vector/cplex_sub.c \
	../complex_vector/cplex_theta.c \
	../complex_vector/cplex_det.c \
	../complex_vector/cplex_vec_add.c \
	../complex_vector/cplex_vec_copy.c \
	../complex_vector/cplex_vec_dot.c \
	../complex_vector/cplex_vec_mag.c \
	../complex_vector/cplex_vec_normalize.c \
	../complex_vector/cplex_vec_set.c \
	../complex_vector/cplex_vec_print.c \
	../complex_vector/cplex_vec_scale.c \
	../complex_vector/cplex_vec_cross.c \
	../complex_vector/cplex_cramer.c

OBJS = obs_point.o \
	../complex_vector/icept.o \
	../complex_vector/surface_icept_pt.o \
	../complex_vector/gradient.o \
	../complex_vector/cplex_add.o \
	../complex_vector/cplex_check.o \
	../complex_vector/cplex_vec_check.o \
	../complex_vector/cplex_div.o \
	../complex_vector/cplex_mag.o \
	../complex_vector/cplex_mult.o \
	../complex_vector/cplex_quad.o \
	../complex_vector/cplex_sq.o \
	../complex_vector/cplex_sqrt.o \
	../complex_vector/cplex_sub.o \
	../complex_vector/cplex_theta.o \
	../complex_vector/cplex_det.o \
	../complex_vector/cplex_vec_add.o \
	../complex_vector/cplex_vec_copy.o \
	../complex_vector/cplex_vec_dot.o \
	../complex_vector/cplex_vec_mag.o \
	../complex_vector/cplex_vec_normalize.o \
	../complex_vector/cplex_vec_set.o \
	../complex_vector/cplex_vec_print.o \
	../complex_vector/cplex_vec_scale.o \
	../complex_vector/cplex_vec_cross.o \
	../complex_vector/cplex_cramer.o

%.o: %.c
	$(CC) -c -o $@ $< $(CFLAGS) $(CPPFLAGS)

obs_point: $(OBJS)
	$(CC) -o $@ $^ $(CFLAGS) $(CPPFLAGS) $(LIBS)

clean:
	rm -f $(OBJS) obs_point ../complex_vector/cplex_vec_null.o \
	../complex_vector/cplex_test.o ../complex_vector/cplex_test \
	../complex_vector/line_plane_icept.o ../complex_vector/cplex_cbrt.o
