
CC=/usr/bin/cc

CFLAGS= -std=iso9899:1999 -m64 -O3 \
	-mhard-float \
	-mno-app-regs -mflat -mhard-quad-float \
	-mno-unaligned-doubles \
	-mcpu=ultrasparc -mtune=ultrasparc -mno-vis -mno-cbcond \
	-mcmodel=medany \
	-mmemory-model=tso \
	-fPIC -Wl,-rpath=/usr/pkg/lib \
	-Wl,-rpath=/usr/X11R7/lib -Wl,-pie

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=600

IDIR=/usr/pkg/include -I/usr/X11R7/include
LDIR=/usr/pkg/lib -L/usr/X11R7/lib
LIBS=-lX11 -lrt -lm -lpthread

include common.mk

