
CFLAGS= -std=iso9899:1999 -O3 -march=rv64imafdc -mabi=lp64d \
-mfdiv -mdiv -mpreferred-stack-boundary=4 -mriscv-attribute \
-malign-data=xlen -mlittle-endian


LIBS = -lX11 -lrt -lm

include common.mk

