CFLAGS= -std=iso9899:1999 -pedantic -pedantic-errors -Weverything \
	-Wno-reserved-id-macro -Wno-missing-prototypes -m32 -g -O0 \
	-fno-fast-math -fno-builtin -Wno-reserved-identifier \
	-Wno-unsafe-buffer-usage

include common.mk
