
CFLAGS= -std=iso9899:1999 -pedantic -pedantic-errors -g -O0 \
-march=rv64imafdc -mabi=lp64d -fno-builtin -fno-fast-math \
-ffp-contract=off -fno-unsafe-math-optimizations \
-mpreferred-stack-boundary=4

LIBS = -lX11 -lrt -lm

include common.mk

