
CC?=/opt/bw/gcc13/bin/gcc

CFLAGS= -std=iso9899:1999 -g -O0 -m64 -fno-builtin -fno-fast-math \
	-ffp-contract=off -fno-unsafe-math-optimizations -malign-double \
	-march=k8 -mtune=k8 -mieee-fp -mhard-float -mpc80 \
	-m128bit-long-double -mlong-double-80 -mstackrealign \
	-mpreferred-stack-boundary=8

CPPFLAGS= -D_XOPEN_SOURCE=600 -D_LARGEFILE64_SOURCE

include common.mk
