
CC?=/usr/bin/cc

CFLAGS= -std=iso9899:1999 -m64 -g -O0 -pedantic -pedantic-errors \
	-fno-builtin -fno-fast-math -mhard-float -mno-app-regs -mflat \
	-msoft-quad-float -mno-unaligned-doubles -mno-faster-structs \
	-mcpu=ultrasparc -mtune=ultrasparc -mno-vis -mno-cbcond \
	-mno-fmaf -mno-fsmuld -mno-popc -mno-subxc -mcmodel=medany \
	-mmemory-model=tso \
	-fPIC -Wl,-rpath=/usr/lib64 \
	-Wl,-rpath=/usr/lib64 -Wl,-pie

CPPFLAGS= -D_LARGEFILE64_SOURCE -D_XOPEN_SOURCE=600

IDIR=/usr/include -I/usr/include/X11
LDIR=/usr/lib64 -L/usr/lib64
LIBS=-lX11 -lrt -lm -lpthread

include common.mk

