
CC?=/usr/bin/gcc

CFLAGS= -std=iso9899:2011 -m64 -O3

CPPFLAGS= -D_LARGEFILE64_SOURCE

IDIR=/usr/include -I/usr/include/X11
LDIR=/usr/lib64 -L/usr/lib64
LIBS=-lX11 -lrt -lm -lpthread

include common.mk

