
CFLAGS= -std=iso9899:1999 -pedantic -pedantic-errors -m64 -g -O0 \
	-Weverything -Wno-reserved-identifier -Wno-unused-variable \
	-Wno-reserved-id-macro -Wno-missing-prototypes \
	-fno-fast-math -fno-builtin -fno-color-diagnostics

CPPFLAGS= -D_XOPEN_SOURCE=600 -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64

include common.mk

